#!/bin/bash
class_name=$1
create_path="src/js/$2"
template="
import React from 'react'

class $class_name extends React.Component{
	render(){
		return (
			<div>$class_name</div>
		)
	}
}

export default $class_name
"
file_name="$create_path/$class_name.jsx"
if [ ! -d $create_path ];then 
    echo "Error: directory $create_path does not exist.";
    exit; 
fi
if [ -e $file_name ];then 
    echo "Error: $file_name has been existed."
    exit 
fi
echo "$template" > $file_name && echo "Create $file_name."
